### ISSUE TITLE
The calculation error of DielectricCylinder does not support analysis of non-neutral systems

### ISSUE THREAD

**Issue by hejamu** [maicos-devel/maicos#107]
In GitLab by @zdxing1 on Apr 3, 2024, 03:32 UTC

An error occurred when using DielectricCylinder to calculate the dielectric constant of water molecules. The code and error are as follows
`
import matplotlib.pyplot as plt
import MDAnalysis as mda
import maicos
import numpy as np

u = mda.Universe("D:/jisuanwuli/vmd1/water.psf", "D:/jisuanwuli/vmd1/c20t.dcd" )

water = u.select_atoms("resname XXXX and not (type NA) ")

epc = maicos.DielectricCylinder(
    water, bin_width=0.1, refgroup=water).run()

Traceback (most recent call last):
  File "D:\jisuanwuli\ceshi.py", line 13, in <module>
    water, bin_width=0.1, refgroup=water).run()
  File "D:\python\Lib\site-packages\maicos\core\base.py", line 245, in run
    self._prepare()
  File "D:\python\Lib\site-packages\maicos\lib\util.py", line 453, in wrapped
    raise ValueError(
ValueError: Analysis for non-neutral systems is not supported.
`
`u.select_atoms("resname XXXX and not (type NA) ")`is the SPC/e water molecule that needs to be calculated.

May I ask what caused the error? Thanks.

*Migrated from GitLab: https://gitlab.com/maicos-devel/maicos/-/issues/129*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Apr 4, 2024, 04:46 UTC

As the error tells you

> Analysis for non-neutral systems is not supported.

The reason is that the equations for calculating dielectric constants only hold if there are no free charges (ions, charged molecules etc) present.

What I see in your message is that you have ions in your system. This unfortunately does not work.

**Comment by hejamu** [comment]
In GitLab by @zdxing1 on Apr 4, 2024, 05:04 UTC

So I can't have ions in the topology file and the trajectory file?

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Apr 4, 2024, 05:08 UTC

Yes, once you have ions in your simulation the equations do not hold anymore.

**Comment by hejamu** [comment]
In GitLab by @zdxing1 on Apr 4, 2024, 05:14 UTC

Ok, thanks for your reply!

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Apr 4, 2024, 07:13 UTC

Always!
