### ISSUE TITLE
Added velocity  module - [merged]

### ISSUE THREAD

**Issue by hejamu** [maicos-devel/maicos#155]
In GitLab by @PicoCentauri on Oct 13, 2019, 18:46 UTC

_Merges velocity -> develop_

Fixes #10 

Changes made in this Pull Request:
Added a module to calculate the velocityprofile

PR Checklist
------------
 - [x] Docs?
 - [x] Issue raised/referenced?

*Migrated from GitLab: https://gitlab.com/maicos-devel/maicos/-/merge_requests/35*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 14, 2019, 15:01 UTC

added 1 commit

<ul><li>3dc28dce - Continued work on module</li></ul>

[Compare with previous version](/ag-netz/mdtools/merge_requests/35/diffs?diff_id=470&start_sha=c487c8d3e13a2d50aee0ea8cc1330dfc6aea34af)

 *By Philip Loche on 2019-10-14T15:01:13 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 16, 2019, 11:55 UTC

added 1 commit

<ul><li>b513e523 - Added bash completion and fixed errors</li></ul>

[Compare with previous version](/ag-netz/mdtools/merge_requests/35/diffs?diff_id=477&start_sha=3dc28dce6c49fd238fcd9576d134251719c2c985)

 *By Philip Loche on 2019-10-16T11:55:30 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 16, 2019, 12:13 UTC

In principle it is working but I got errors when trying to calculate the error estimate:

```bash
philiploche@z48bc:~/repos/mdtools$ mdtools velocity -f tests/data/water/traj.trr -s tests/data/water/topol.tpr --debug

Command line was: mdtools velocity -f tests/data/water/traj.trr -s tests/data/water/topol.tpr

Loading trajectory... Done!

Performing analysis for the following group(s):
            all:       1530 atoms
Step   101/101 [100.0%]

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mdtools/__main__.py", line 247, in main
    ana_obj.run(begin=args.begin, end=args.end, dt=args.dt)
  File "/usr/local/lib/python3.7/site-packages/mdtools/modules/base.py", line 135, in run
    self._conclude()
  File "/usr/local/lib/python3.7/site-packages/mdtools/modules/transport.py", line 228, in _conclude
    max_nfev=1e5,
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 763, in curve_fit
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_lsq/least_squares.py", line 813, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
ValueError: Residuals are not finite in the initial point.

Starting interactive Python interpreter for debug.⁠
You can access all your analysis class atrributes via ana_obj.<attributes>.
```

The problem seems to be that `self.results["ee_out"]` contains a `0` as its first element. This obviously comes from the `_blockee` functions which first element is alway zero... @aschlaich Do you have an idea?

 *By Philip Loche on 2019-10-16T12:13:54 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 28, 2019, 07:49 UTC

Isn't the reason simply that the blocm error estimate should start with 1 block instead of zero? I.e. the loop variable should start from one and you need to adapt the upper limit correspondingly?

Btw, I guess it would be nice to move the blockee stuff to out of the transport module into the general helper stuff.

 *By Schlaich, Alexander on 2019-10-28T07:49:04 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 28, 2019, 10:15 UTC

added 13 commits

<ul><li>b513e523...6641c961 - 8 commits from branch <code>ag-netz:develop</code></li><li>5a535898 - Added velocity profile</li><li>fd1dc800 - Continued work on module</li><li>be21a6ed - Added bash completion and fixed errors</li><li>34544ac4 - Fixed error estimate</li><li>491019bd - Merge branch &#39;velocity&#39; of gitlabph.physik.fu-berlin.de:ploche/mdtools into velocity</li></ul>

[Compare with previous version](/ag-netz/mdtools/merge_requests/35/diffs?diff_id=503&start_sha=b513e52317ef78e879af6047c0f2fd2bf03ab13b)

 *By Philip Loche on 2019-10-28T10:15:30 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 28, 2019, 10:16 UTC

added 1 commit

<ul><li>20551989 - Added new line</li></ul>

[Compare with previous version](/ag-netz/mdtools/merge_requests/35/diffs?diff_id=504&start_sha=491019bdaa7619590e28dac4e95ccd6234e44bf6)

 *By Philip Loche on 2019-10-28T10:16:59 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 28, 2019, 10:19 UTC

Thanks for the help. I Fixed the problem. Actually I didn't not use the correct `dt` variable of the object...

 >  Btw, I guess it would be nice to move the blockee stuff to out of the transport module into the general helper stuff.

Definitely!!! I will raise an issue.

 *By Philip Loche on 2019-10-28T10:19:11 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 28, 2019, 10:19 UTC

unmarked as a **Work In Progress**

 *By Philip Loche on 2019-10-28T10:19:37 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 28, 2019, 10:20 UTC

mentioned in commit 295fa4fc8c205adb183dbd2c489e90d3ca89b0a7

 *By Philip Loche on 2019-10-28T10:20:16 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 28, 2019, 10:20 UTC

merged

 *By Philip Loche on 2019-10-28T10:20:17 (imported from GitLab project)*
