### ISSUE TITLE
python2 compatibility

### ISSUE THREAD

**Issue by hejamu** [maicos-devel/maicos#16]
In GitLab by @PicoCentauri on Nov 21, 2018, 11:28 UTC

---
name: Bug report
about: python2 compatibility from the command line

---

**Expected behavior**

mdtools command line interface should work with python2?!

**Actual behavior**

It does not

**Code to reproduce the behavior**

``` bash
philip@Philips-MacBook-Pro:~$ mdtools density_planar -h
/Users/philip/Library/Python/2.7/lib/python/site-packages/MDAnalysis/due.py:88: UserWarning: No module named duecredit
  warnings.warn(str(err))

Command line was: mdtools density_planar -h

Traceback (most recent call last):
  File "/usr/local/bin/mdtools", line 11, in <module>
    load_entry_point('mdtools==0.1.dev0', 'console_scripts', 'mdtools')()
  File "/usr/local/lib/python2.7/site-packages/mdtools-0.1.dev0-py2.7.egg/mdtools/__main__.py", line 110, in main
    _configure_parser(met, parser)
TypeError: unbound method _configure_parser() must be called with density_planar instance as first argument (got type instance instead)
```

This issue is open for discussion. If somebody knows how to fix this easily (probably me), we can keep python2... Otherwise I'm also okay with dropping it.

*Migrated from GitLab: https://gitlab.com/maicos-devel/maicos/-/issues/15*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jan 22, 2019, 10:13 UTC

Since python2 will be deprecated in [11 month](https://pythonclock.org). This will not be fixed

 *By Philip Loche on 2019-01-22T10:13:53 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jan 22, 2019, 10:13 UTC

closed

 *By Philip Loche on 2019-01-22T10:13:56 (imported from GitLab project)*
