### ISSUE TITLE
versioning seems to be broken

### ISSUE THREAD

**Issue by hejamu** [maicos-devel/maicos#25]
In GitLab by @PicoCentauri on Feb 22, 2019, 15:38 UTC

```
leonard:~> .local/bin/mdtools 
Traceback (most recent call last):
  File ".local/bin/mdtools", line 6, in <module>
    from mdtools.__main__ import main
  File "/home/aschlaich/.local/lib/python3.6/site-packages/mdtools/__init__.py", line 6, in <module>
    from . import __version__
ImportError: cannot import name '__version__'
```

*Migrated from GitLab: https://gitlab.com/maicos-devel/maicos/-/issues/24*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Feb 23, 2019, 18:42 UTC

mentioned in commit 635d579d17d196595b17be879ed17eecd9df9cf1

 *By Philip Loche on 2019-02-23T18:42:39 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Feb 23, 2019, 18:42 UTC

closed via merge request !24

 *By Philip Loche on 2019-02-23T18:42:39 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Feb 26, 2019, 14:23 UTC

reopened

 *By Schlaich, Alexander on 2019-02-26T14:23:41 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Feb 26, 2019, 14:38 UTC

Reopened as the problem persists. !26 should hopefully fix all imports.

 *By Schlaich, Alexander on 2019-02-26T14:38:38 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Feb 26, 2019, 15:30 UTC

closed via merge request !26

 *By Philip Loche on 2019-02-26T15:30:34 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Feb 26, 2019, 15:30 UTC

closed via commit 4531fa9785b0a2bcaf7d71b82d553931d59fa029

 *By Philip Loche on 2019-02-26T15:30:34 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Feb 26, 2019, 15:30 UTC

closed via commit b4c3d2fd79b735954c491eb7e4e71705c09f7584

 *By Philip Loche on 2019-02-26T15:30:35 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 30, 2019, 10:09 UTC

mentioned in commit 4531fa9785b0a2bcaf7d71b82d553931d59fa029

 *By Philip Loche on 2019-10-30T10:09:32 (imported from GitLab project)*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Oct 30, 2019, 10:09 UTC

mentioned in commit b4c3d2fd79b735954c491eb7e4e71705c09f7584

 *By Philip Loche on 2019-10-30T10:09:32 (imported from GitLab project)*
