### ISSUE TITLE
Fix error estimate - [merged]

### ISSUE THREAD

**Issue by hejamu** [maicos-devel/maicos#259]
In GitLab by @PicoCentauri on Aug 12, 2022, 11:03 UTC

_Merges fix_error_estimate -> main_

Fixes #89 

Changes made in this Pull Request:
 - Use correct error propagation in EpsilonPlanar

Error looks reasoanble now (blue bars are the errors).

![13aa0536-032b-405d-a455-c8738c012593](https://s3.eu-north-1.amazonaws.com/maicos-gitlab-bucket/980597715/e735a0b022176c135cbf87fe74bd3e9b0c8f8ef14d96be256d02b7e05ce55a28/13aa0536-032b-405d-a455-c8738c012593.png)
![3ae83fe1-5e12-4e62-9549-5af8aab7f770](https://s3.eu-north-1.amazonaws.com/maicos-gitlab-bucket/980597715/1b45ea059cec9365976c8dd77ce738f1a4d6b6e840cfd92c5e666b38db00b99d/3ae83fe1-5e12-4e62-9549-5af8aab7f770.png)

Code for the plots

```python
datapath = "../../../../tests/data/airwater"
u = mda.Universe(f'{datapath}/topol.tpr', f'{datapath}/traj.trr')

eplan = maicos.EpsilonPlanar(u.atoms).run()
                 
plt.errorbar(eplan.results.z,
             eplan.results.eps_par.flatten(),
             yerr=eplan.results.deps_par.flatten())
plt.plot(eplan.results.z,
         eplan.results.eps_par.flatten(),c="red",zorder=10)

plt.ylabel("eps_par")
plt.xlabel("z")
plt.show()


plt.errorbar(eplan.results.z,
             eplan.results.eps_perp.flatten(),
             yerr=eplan.results.deps_perp.flatten())
plt.plot(eplan.results.z,
         eplan.results.eps_perp.flatten(),c="red",zorder=10)

plt.ylabel("eps_perp")
plt.xlabel("z")
plt.show()
```

*Migrated from GitLab: https://gitlab.com/maicos-devel/maicos/-/merge_requests/153*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 12, 2022, 11:08 UTC

Please @schlaicha could you run this with your large test trajectory?

An idea (besides a simple regression test) to test the errors would be to set the values of 
`sems.mM_perp`, `means.mM_perp` etc with chosen values and run the `_conclude` function. We then should compare the 
errors with explicitly calculated values. @hejamu volunteered for doing this :-)

**Comment by hejamu** [comment]
In GitLab by @codecov on Aug 12, 2022, 11:11 UTC

# [Codecov](https://codecov.io/gl/maicos-devel/maicos/pull/153?src=pr&el=h1&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS) Report
> Merging [#153](https://codecov.io/gl/maicos-devel/maicos/pull/153?src=pr&el=desc&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS) (df3e43b) into [main](https://codecov.io/gl/maicos-devel/maicos/commit/789d3c0911d9ad087936fa171c47df0f3c0bef05?el=desc&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS) (789d3c0) will **decrease** coverage by `0.01%`.
> The diff coverage is `n/a`.

```diff
@@            Coverage Diff             @@
##             main     #153      +/-   ##
==========================================
- Coverage   92.34%   92.33%   -0.02%     
==========================================
  Files          12       12              
  Lines        1333     1331       -2     
  Branches      213      213              
==========================================
- Hits         1231     1229       -2     
  Misses         60       60              
  Partials       42       42              
```


| [Impacted Files](https://codecov.io/gl/maicos-devel/maicos/pull/153?src=pr&el=tree&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS) | Coverage Δ | |
|---|---|---|
| [maicos/modules/base.py](https://codecov.io/gl/maicos-devel/maicos/pull/153/diff?src=pr&el=tree&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS#diff-bWFpY29zL21vZHVsZXMvYmFzZS5weQ==) | `98.38% <ø> (-0.02%)` | :arrow_down: |
| [maicos/modules/epsilon.py](https://codecov.io/gl/maicos-devel/maicos/pull/153/diff?src=pr&el=tree&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS#diff-bWFpY29zL21vZHVsZXMvZXBzaWxvbi5weQ==) | `95.25% <ø> (ø)` | |

Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=MAICoS)

**Comment by hejamu** [comment]
In GitLab by @schlaicha on Aug 15, 2022, 19:05 UTC

These changes break epsilon for me with the same error that causes the test to fail:

```
Traceback (most recent call last):
  File "../epsilon_planar.py", line 50, in <module>
    eps.run(verbose=True, step=step)
  File "/tikhome/schlaich/repos/tools/maicos/maicos/modules/base.py", line 174, in run
    self._conclude()
  File "/tikhome/schlaich/repos/tools/maicos/maicos/modules/epsilon.py", line 351, in _conclude
    + np.dot(self.results.means.M_par**2,
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (2,) and (55,2) not aligned: 2 (dim 0) != 55 (dim 0)
```

**Comment by hejamu** [comment]
added 1 commit

<ul><li>df3e43b7 - Change order in dot product</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/153/diffs?diff_id=461675531&start_sha=0158b9736d0417b7a93c2c5de745dc39225826a1)

**Comment by hejamu** [comment]
@PicoCentauri, so there was a reason for this order after all...

@schlaicha you can test it at your convenience

**Comment by hejamu** [comment]
In GitLab by @schlaicha on Aug 15, 2022, 20:20 UTC

Like a charm!

**Comment by hejamu** [comment]
In GitLab by @schlaicha on Aug 15, 2022, 20:20 UTC

approved this merge request

**Comment by hejamu** [comment]
In GitLab by @schlaicha on Aug 15, 2022, 20:22 UTC

mentioned in commit c2b7132853b4af9495e9080e3553719677bfaee7
