### ISSUE TITLE
-e should throw an error if endframe < startframe

### ISSUE THREAD

**Issue by hejamu** [maicos-devel/maicos#38]
In GitLab by @schlaicha on Mar 29, 2021, 19:32 UTC

I don't get the logics involved behind this but whenever calling a module with -e this error gets thrown:
```
Traceback (most recent call last):
  File "/tikhome/schlaich/.local/lib/python3.8/site-packages/maicos/__main__.py", line 269, in main
    ana_obj.run(begin=args.begin, end=args.end, dt=args.dt)
  File "/tikhome/schlaich/.local/lib/python3.8/site-packages/maicos/modules/base.py", line 140, in run
    self._calculate_results()
  File "/tikhome/schlaich/.local/lib/python3.8/site-packages/maicos/decorators.py", line 135, in _calculate_results
    self._index = self._frame_index + 1                                                                                       │
AttributeError: 'diporder' object has no attribute '_frame_index'
```

Apparently the test for this is in `tests/modules/test_structure.py` and seems to pass, so I boiled it down to a presumable error in passing the maicos command line script. However, I don't recall how this was reconstructed @PicoCentauri

*Migrated from GitLab: https://gitlab.com/maicos-devel/maicos/-/issues/40*

**Comment by hejamu** [comment]
In GitLab by @schlaicha on Mar 31, 2021, 06:51 UTC

Turned out the error gets thrown if endframe < startframe, i.e. we should throw an appropriate error in this case as proposed in !53
